#!/usr/bin/expect -f

# Set variables
 set hostname [lindex $argv 0]
 set username $env(USER)
 set password [lindex $argv 1]
 set enablepassword [lindex $argv 2]

# Log results
 log_file -a ~/EA_Code/EA_Code_Log.log

# Announce which device we are working on and at what time
 send_user "\n"
 send_user ">>>>>  Working on $hostname @ [exec date] <<<<<\n"
 send_user "\n"

# Telnet
spawn telnet $hostname
sleep 1

expect {
"Connection refused" {
spawn ssh $hostname

expect {
"no)? " { 
send "yes\n"
expect "*assword: "
send "$password\r"
}
"*assword: " { 
send "$password\n"
}
}
}

"sername:" {
send "$username\r"
expect "*assword: "
send "$password\r"
}
}

#If we're not already in enable mode, get us there
expect {
default { send_user "\nEnable Mode Failed - Check Password\n"; exit 1 }
"*#" {}
"*>" {
send "enable\n"
expect "*assword"
send "$enablepassword\n"
expect "*#"
}
}

# Code
send "show ver | i cisco |kickstart:|NXOS:|hassis|flash:\n"
expect "#"
send "exit\n"
expect ":~\$"
exit
