#!/bin/bash
 # Collect the current user's ssh and enable passwords
 echo -n "Enter the SSH password for $(whoami) "
 read -s -e password
 echo -ne '\n'
 echo -n "Enter the Enable password for $(whoami) "
 read -s -e enable
 echo -ne '\n'
# Feed the expect script a device list & the collected passwords


for device in `cat ~/Code/devices.txt`; do
 ./code_exp.exp $device $password $enable ;
 done

egrep -A2 "hkg1#.*show" Code_Log.log | egrep -v "\--" | sed 's/#.*//g;s/^.*is //g;s/(.*//g' > Code_Out_Temp
